version: '3.7'

services:
  gazebo:
    image: ros_noetic_gazebo_demo
    build: .
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - XDG_RUNTIME_DIR=/tmp/runtime-root
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "
      mkdir -p /tmp/runtime-root && chmod 0700 /tmp/runtime-root && 
      source /opt/ros/noetic/setup.bash && 
      source /root/ros_ws/devel/setup.bash && 
      roslaunch /root/ros_ws/gazebo_demo.launch"